language: php
sudo: required

matrix:
  include:
    - php: 5.3
      env: DB=mysqli
    - php: 5.4
      env: DB=mysqli
    - php: 5.4
      env: DB=mysql
    - php: 5.4
      env: DB=mariadb
    - php: 5.4
      env: DB=postgres
    - php: 5.4
      env: DB=sqlite3
    - php: 5.5
      env: DB=mysqli
    - php: 5.6
      env: DB=mysqli
    - php: 7.0
      env: DB=mysqli
    - php: hhvm
      env: DB=mysqli
  allow_failures:
    - php: hhvm
    - php: 7.0
  fast_finish: true

env:
  global:
    - SNIFF="1"            # Should we run code sniffer on your code?
    - IMAGE_ICC="1"        # Should we run icc profile sniffer on your images?
    - EPV="1"              # Should we run EPV (Extension Pre Validator) on your code?

branches:
  only:
    - master
    - develop
    - /^dev\/.*$/
    - /^issue\/.*$/

install:
  - composer install --dev --no-interaction --prefer-source
  - mkdir survey
  - mv `find . -maxdepth 1 ! -name . ! -name survey` survey
  - mkdir -p survey/travis
  - git clone --depth=1 "git://github.com/phpbb/phpbb.git" --branch=3.1.x
  - cp -R phpbb/travis/* survey/travis
  - mkdir phpbb/phpBB/ext/kilianr
  - mv survey phpbb/phpBB/ext/kilianr
  - cd phpbb
  - travis/setup-phpbb.sh $DB $TRAVIS_PHP_VERSION

before_script:
  - travis/setup-database.sh $DB $TRAVIS_PHP_VERSION

notifications:
  slack:
    on_success: change
    on_failure: change

script:
  - sh -c "if [ '$SNIFF' != '0' ]; then travis/ext-sniff.sh $DB $TRAVIS_PHP_VERSION kilianr/survey; fi"
  - sh -c "if [ '$IMAGE_ICC' != '0' ]; then travis/check-image-icc-profiles.sh $DB $TRAVIS_PHP_VERSION; fi"
  - phpBB/vendor/bin/phpunit --configuration phpBB/ext/kilianr/survey/travis/phpunit-$DB-travis.xml --bootstrap ./tests/bootstrap.php
  - sh -c "if [ '$EPV' != '0' ] && [ '$TRAVIS_PHP_VERSION' = '5.3.3' ] && [ '$DB' = 'mysqli' ]; then phpBB/ext/kilianr/survey/vendor/bin/EPV.php run --dir='phpBB/ext/$EXTNAME/'; fi"
