parameters:
    tables.kilianr.survey.surveys: %core.table_prefix%surveys
    tables.kilianr.survey.questions: %core.table_prefix%surveys_questions
    tables.kilianr.survey.question_choices: %core.table_prefix%surveys_q_choices
    tables.kilianr.survey.entries: %core.table_prefix%surveys_entries
    tables.kilianr.survey.answers: %core.table_prefix%surveys_answers
